typography_spectrum: 0.7121935810428113
color:
  brandStrength: 0.9252949135843664
  lightness: 0.2281513235066086
  saturation: 0.7885021029505879
  rhythmicContrast: 0.6803571179043502
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.5912761960644275
name: The Live Lab
navigation:
  - name: The Live Lab @ Facebook
    url: 'https://www.facebook.com/TheLiveLab/?fref=ts'
    type: external
  - name: The Live Lab @ Audiu
    url: 'https://audiu.net/users/thelivelab'
    type: external
  - name: The Live Lab @ Twitter
    url: 'https://twitter.com/the_live_lab'
    type: external
title: Personalised Ableton Live Support
description: Get there!
